/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as BudgetRoundsIndexRouteImport } from './routes/budget-rounds.index'
import { Route as BudgetRoundsRoundIdRouteImport } from './routes/budget-rounds.$roundId'
import { Route as PetitionsIndexRouteImport } from './routes/petitions.index'
import { Route as PetitionsPetitionIdRouteImport } from './routes/petitions.$petitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoundsIndexRoute = BudgetRoundsIndexRouteImport.update({
  id: '/budget-rounds/',
  path: '/budget-rounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoundsRoundIdRoute = BudgetRoundsRoundIdRouteImport.update({
  id: '/budget-rounds/$roundId',
  path: '/budget-rounds/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsIndexRoute = PetitionsIndexRouteImport.update({
  id: '/petitions/',
  path: '/petitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsPetitionIdRoute = PetitionsPetitionIdRouteImport.update({
  id: '/petitions/$petitionId',
  path: '/petitions/$petitionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed': typeof FeedRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/budget-rounds/$roundId': typeof BudgetRoundsRoundIdRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
  '/budget-rounds/': typeof BudgetRoundsIndexRoute
  '/petitions/': typeof PetitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed': typeof FeedRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/budget-rounds/$roundId': typeof BudgetRoundsRoundIdRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
  '/budget-rounds': typeof BudgetRoundsIndexRoute
  '/petitions': typeof PetitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed': typeof FeedRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/budget-rounds/$roundId': typeof BudgetRoundsRoundIdRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
  '/budget-rounds/': typeof BudgetRoundsIndexRoute
  '/petitions/': typeof PetitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/atom.xml'
    | '/feed'
    | '/privacy'
    | '/profile'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/status'
    | '/submit'
    | '/terms'
    | '/vision'
    | '/budget-rounds/$roundId'
    | '/petitions/$petitionId'
    | '/budget-rounds/'
    | '/petitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/atom.xml'
    | '/feed'
    | '/privacy'
    | '/profile'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/status'
    | '/submit'
    | '/terms'
    | '/vision'
    | '/budget-rounds/$roundId'
    | '/petitions/$petitionId'
    | '/budget-rounds'
    | '/petitions'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/atom.xml'
    | '/feed'
    | '/privacy'
    | '/profile'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/status'
    | '/submit'
    | '/terms'
    | '/vision'
    | '/budget-rounds/$roundId'
    | '/petitions/$petitionId'
    | '/budget-rounds/'
    | '/petitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  FeedRoute: typeof FeedRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  BudgetRoundsRoundIdRoute: typeof BudgetRoundsRoundIdRoute
  PetitionsPetitionIdRoute: typeof PetitionsPetitionIdRoute
  BudgetRoundsIndexRoute: typeof BudgetRoundsIndexRoute
  PetitionsIndexRoute: typeof PetitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-rounds/': {
      id: '/budget-rounds/'
      path: '/budget-rounds'
      fullPath: '/budget-rounds/'
      preLoaderRoute: typeof BudgetRoundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-rounds/$roundId': {
      id: '/budget-rounds/$roundId'
      path: '/budget-rounds/$roundId'
      fullPath: '/budget-rounds/$roundId'
      preLoaderRoute: typeof BudgetRoundsRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions/': {
      id: '/petitions/'
      path: '/petitions'
      fullPath: '/petitions/'
      preLoaderRoute: typeof PetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions/$petitionId': {
      id: '/petitions/$petitionId'
      path: '/petitions/$petitionId'
      fullPath: '/petitions/$petitionId'
      preLoaderRoute: typeof PetitionsPetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AtomDotxmlRoute: AtomDotxmlRoute,
  FeedRoute: FeedRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  BudgetRoundsRoundIdRoute: BudgetRoundsRoundIdRoute,
  PetitionsPetitionIdRoute: PetitionsPetitionIdRoute,
  BudgetRoundsIndexRoute: BudgetRoundsIndexRoute,
  PetitionsIndexRoute: PetitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
